# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markedquestion',
            old_name='num_vars',
            new_name='_num_vars',
        ),
    ]
