# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-10 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20170810_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='markedquestion',
            old_name='problem_str',
            new_name='_problem_str',
        ),
        migrations.RenameField(
            model_name='markedquestion',
            old_name='_num_vars',
            new_name='num_vars',
        ),
    ]
